# Generated by Django 5.1.6 on 2025-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_stud_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='total',
            field=models.BigIntegerField(blank=True),
        ),
    ]
