# Generated by Django 5.1.6 on 2025-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_stud_division_alter_stud_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
